captcha:
  key-long: 4
  img-width: 120
  img-height: 40
casbin:
  model-path: ./resource/rbac_model.conf
cron:
  spec_all: 31 23 * * ?
jwt:
  signing-key: qmPlus
log:
  prefix: '[Taylors-LOG]'
  log-file: true
  stdout: DEBUG
  file: DEBUG
module:
  crawler: 127.0.0.1:8888
mysql:
  username: root
  password: password
  path: 192.168.243.131:3306
  db-name: taylors
  config: charset=utf8&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true
qiniu:
  access-key: 25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ
  secret-key: pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY
  bucket: qm-plus-img
  img-path: http://qmplusimg.henrongyi.top
redis:
  addr: 192.168.1.97:6379
  password: ""
  db: 0
sqlite:
  username: ""
  password: ""
  path: db.db
  config: loc=Asia/Shanghai
  log-mode: true
system:
  use-multipoint: false
  env: public
  addr: 9999
  db-type: mysql
